### ISSUE TITLE
c.DockerSpawner.notebook_dir not working with JupyterHub 0.8

### ISSUE THREAD

**Issue by bbhopesh** [jupyterhub/jupyterhub-deploy-docker#52]
Hi,

I am following this repo to  setup my JupyterHub instance on a single server.

Recently, the repo was upgraded to JupyterHub 0.8 and I followed the changes. However, since the upgrade, the parameter `c.DockerSpawner.notebook_dir` doesn't seem to have an effect and the single user servers are always started at `/home/jovyan` instead of `/home/jovyan/work` 

I tried giving different values to the configuration param but it always starts at home directory.

I rollbacked my system to old code before the changes made in last few days and it worked again.

Any help is appreciated.

Thanks,
Bhopesh

**Comment by bbhopesh** [comment]
So, I figured a fix by trial and error but I don't know why my fix is working. There's some problem with the `start-singleuser.sh` script.

Removing following two lines from `jupyterhub_config.py` starts the single user notebook servers at `/home/jovyan/work`, otherwise single user notebook servers always start at `/home/jovyan` irrespective of value of `c.DockerSpawner.notebook_dir`.

### Lines to be removed from `jupyterhub_config.py`
``` python
spawn_cmd = os.environ.get('DOCKER_SPAWN_CMD', "start-singleuser.sh")
c.DockerSpawner.extra_create_kwargs.update({ 'command': spawn_cmd })
```

**Comment by bbhopesh** [comment]
@minrk I am not sure if you are the right person to direct this issue to, but you are the most famous on the repo :) Please help or redirect to someone.

Thanks

**Comment by minrk** [comment]
You are exactly right. The spawn cmd is only constructed from things like notebook_dir if `command` has not been specified by hand, which takes higher priority. We should do better here, either by:

1. identifying the collision and logging a warning, or
2. treating `extra_create_kwargs.command` specially

In general, I think we should discourage the use of `extra_create_kwargs.command`, which skips over all of the configuration DockerSpawner does to build the program to launch.

Setting `c.DockerSpawner.cmd = 'start-singleuser.sh` should get the desired behavior, rather than talking directly to docker bypassing DockerSpawner, which is what `extra_create_kwargs` is for. However, from the looks of it, this is using one of the jupyter docker-stacks (or something based on them), in which case no special command should be needed at all, as the defaults will work correctly.

**Comment by bbhopesh** [comment]
Yes the defaults are working correctly. 

But even the defaults are calling this script indirectly. Why would setting it explicitly create a problem?

**Comment by minrk** [comment]
> Why would setting it explicitly create a problem?

It's not why, it's how. By default, DockerSpawner builds the command to launch the docker image from config such as `c.DockerSpawner.cmd`, `c.DockerSpawner.ip`, etc. There are also some options that allow you to *bypass* any logic in DockerSpawner, and talk directly to Docker. `extra_create_kwargs` is one such option. By specifying `extra_create_kwargs.command`, you are saying that you have decided what the command to launch should be, and that DockerSpawner should not try to build the `command` itself.

**Comment by bbhopesh** [comment]
I see. Thanks a lot for your help.
Should I send a PR with the change?
