### ISSUE TITLE
Persisting container changes

### ISSUE THREAD

**Issue by sconeyard** [jupyterhub/jupyterhub-deploy-docker#61]
Jupyter Notebook has the option of starting and running a terminal. This is useful to install packages using pip or download large files via wget/curl. However, while data seems to be persisted, installed packages vanish after restarting a user-container. Can we fix this? 
I think we need to commit the changes, after shutdown. Is there by any chance an option to run stuff after a single notebook (in this case user-container) was shut down?

**Comment by dalg24** [comment]
> install packages using pip or download large files via wget/curl.

Anything you want to persist has to to be under the user's notebook directory (`/home/jovyan/work`).
When you install a package using pip, you are able to specify the installation prefix (passing the option `--prefix=/home/jovyan/work/.local` is one way achieve this).  Then, in order to use it in a notebook, append your installation prefix to your path (by executing `sys.path.append("/home/jovyan/work/.local/lib/pythonX.Y/site-packages")` in a cell before you attempt to import that package.   Do not forget to adjust the Python version `X.Y` as necessary.)

You may also consider extending the notebook image.

**Comment by willingc** [comment]
Thanks @dalg24 for sharing the response. @sconeyard I hope this helps you.
