### ISSUE TITLE
Update for production or deprecate this repo 

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub-deploy-docker#63]
This repo was created to provide a reference (not production) deployment when using JupyterHub with Docker. We've made significant improvements in deploying JupyterHub on Kubernetes [reference Zero To JupyterHub](https://github.com/jupyterhub/zero-to-jupyterhub-k8s).

Question: what should be the future of this repo?

If keeping around as a reference deployment:

- Update this reference deployment to JupyterHub 0.8.1
- Create a more prominent disclaimer/warning/intended usage message in README.

Otherwise:

- Archive the repo

cc/ @minrk

**Comment by sconeyard** [comment]
I just deployed this on a machine, with some adjustments I got to run this without the need for GitHub accounts (but users on the machine, not production really, but enough to share ressources amongst a few people). Also by adjusting the singleuser jupyterhub Dockerfile to ultimately use the Nvidia-Docker it works fine with GPUs. I think you shouldn't retire this git, as it is sufficient to support a few users, sharing one machine (small classes, friends, low-demanding work groups). Maybe put up a more prominent disclaimer, but please don't retire this.

That said, are there any breaking changes in 0.8.1? Otherwise we just need to update the .env variable for starters.

**Comment by moppymopperson** [comment]
Yeah, I'd like to see this stick around too. It's perfect for my use case.

**Comment by obilodeau** [comment]
We use this repository to create the students' environments during a workshop.

A few days before the workshop I provision a small cloud server with docker / docker-compose, deploy this and copy our lab files to a shared folder. The day before the lab I resize the server to the largest instance available. After the lab, I resize it back to a small one.

This allows us to pay less than 10$ for the full setup and it only required 2 days to learn / setup the first time (including image customization) and now I can deploy the whole thing in under 2 hours. I was already familiar with docker / docker-compose.

I'm not convinced that the complexity of adding in Kubernetes is worth it for my use-case.

**Comment by mbusch-regis** [comment]
Similar to the responses above, I'm at a medium-small university setting up a hub for 1 - 2 classes of 20 students on a dedicated internal server. Docker Swarm and K8s seem extremely over complicated for our case. 

I'd like to see this continue on, updated, possibly with some ballpark parameters for usage.  

For example, in my case we are using a Dell Poweredge r730 with 24 CPUs and 128GB of RAM to support 20 - 40 concurrent users doing light Data Science analysis.

I'll try to remember to report back, positively or negatively, after we've done some testing.

**Comment by willingc** [comment]
Thanks all for your comments. I can see that this repo is important to many so we will continue to maintain (not deprecate) this repo. I'm going to formally close this issue.

Please feel free to contribute docs and suggestions to help keep this up-to-date and helpful for others :cake:
