### ISSUE TITLE
why mount docker.sock in hub container?

### ISSUE THREAD

**Issue by ktrysmt** [jupyterhub/jupyterhub-deploy-docker#68]
Why mount /var/run/docker.sock into container by docker-compose.yml?
* https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/docker-compose.yml#L34

It has been known that it should not be, but... any other reason?

References;
* https://www.lvh.io/posts/dont-expose-the-docker-socket-not-even-to-a-container.html
* https://news.ycombinator.com/item?id=10269200

**Comment by minrk** [comment]
> Why mount /var/run/docker.sock into container by docker-compose.yml?

The docker socket is mounted in the Hub container because the Hub needs to administer docker (create/start/stop/delete containers and volumes). This is done either by mounting the docker socket, or by exposing docker tcp to the Hub container. This is required for JupyterHub to work.

> It has been known that it should not be, but... any other reason?

This is not accurate. It is not a security vulnerability, rather it is standard practice for privileged containers whose role is to administer docker itself, which is the case for the Hub. Note that the docker socket is not mounted in *user* containers, only the Hub which is responsible for managing those containers, and runs no user code. Users should have no access to docker itself in this configuration.
